export const fotos = [
    {id: '1', foto: './imagens/lookBook/foto1.jpg', altura: '60vh'},
    {id: '2', foto: './imagens/lookBook/foto2.jpg', altura: '50vh'},
    {id: '3', foto: './imagens/lookBook/foto3.jpg', altura: '60vh'},
    {id: '4', foto: './imagens/lookBook/foto4.jpg', altura: '50vh'},
    {id: '5', foto: './imagens/lookBook/foto5.jpg', altura: '50vh'},
    {id: '6', foto: './imagens/lookBook/foto6.jpg', altura: '60vh'},
    {id: '7', foto: './imagens/lookBook/foto7.jpg', altura: '60vh'},
    {id: '8', foto: './imagens/lookBook/foto8.jpg', altura: '50vh'},
    {id: '9', foto: './imagens/lookBook/foto9.jpg', altura: '50vh'},
    {id: '10', foto: './imagens/lookBook/foto10.jpg', altura: '40vh'},
    {id: '11', foto: './imagens/lookBook/foto11.jpg', altura: '50vh'},
    {id: '12', foto: './imagens/lookBook/foto12.jpg', altura: '60vh'},
    {id: '13', foto: './imagens/lookBook/foto1.jpg', altura: '60vh'},
    {id: '14', foto: './imagens/lookBook/foto2.jpg', altura: '50vh'},
    {id: '15', foto: './imagens/lookBook/foto3.jpg', altura: '60vh'},
    {id: '16', foto: './imagens/lookBook/foto4.jpg', altura: '50vh'},
    {id: '17', foto: './imagens/lookBook/foto5.jpg', altura: '50vh'},
    {id: '18', foto: './imagens/lookBook/foto6.jpg', altura: '60vh'},
    {id: '19', foto: './imagens/lookBook/foto7.jpg', altura: '60vh'},
    {id: '20', foto: './imagens/lookBook/foto8.jpg', altura: '50vh'},
    {id: '21', foto: './imagens/lookBook/foto9.jpg', altura: '50vh'},
    {id: '22', foto: './imagens/lookBook/foto10.jpg', altura: '40vh'},
    {id: '23', foto: './imagens/lookBook/foto11.jpg', altura: '50vh'},
    {id: '24', foto: './imagens/lookBook/foto12.jpg', altura: '60vh'},
    {id: '25', foto: './imagens/lookBook/foto1.jpg', altura: '60vh'},
    {id: '26', foto: './imagens/lookBook/foto2.jpg', altura: '50vh'},
    {id: '27', foto: './imagens/lookBook/foto3.jpg', altura: '60vh'},
    {id: '28', foto: './imagens/lookBook/foto4.jpg', altura: '50vh'},
    {id: '29', foto: './imagens/lookBook/foto5.jpg', altura: '50vh'},
    {id: '30', foto: './imagens/lookBook/foto6.jpg', altura: '60vh'},
    {id: '31', foto: './imagens/lookBook/foto9.jpg', altura: '60vh'},
    {id: '32', foto: './imagens/lookBook/foto10.jpg', altura: '50vh'},
]

export const fotosHome = [
    {id: '1', foto: './imagens/lookBook/foto11.jpg'},
    {id: '2', foto: './imagens/lookBook/foto12.jpg'},
    {id: '3', foto: './imagens/lookBook/foto1.jpg'},
    {id: '4', foto: './imagens/lookBook/foto3.jpg'},
    {id: '5', foto: './imagens/lookBook/foto5.jpg'},
    {id: '6', foto: './imagens/lookBook/foto4.jpg'},
]

